### ISSUE TITLE
PotionEffectType is missing

### ISSUE THREAD

**Issue by IkeVoodoo** [MockBukkit/MockBukkit#625] opened 2022-09-07 17:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.19

### Describe the bug

Calling

```java
MockBukkit.mock()
```

Resilts in

```java
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.bukkit.event.player.PlayerJoinEvent.<init>(org.bukkit.entity.Player, net.kyori.adventure.text.Component)'
	at be.seeseemelk.mockbukkit.ServerMock.addPlayer(ServerMock.java:274)
	at be.seeseemelk.mockbukkit.ServerMock.addPlayer(ServerMock.java:317)
```

It seems as if `PotionEffectType` is missing

### Reproducible Test

```java
MockBukkit.mock().addPlayer("Player1");

// Some code

MockBukkit.unmock();
```

### Anything else?

My pom repositories & dependencies

```xml
<repositories>
    <repository>
        <id>spigotmc-repo</id>
        <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
    </repository>
    <repository>
        <id>sonatype</id>
        <url>https://oss.sonatype.org/content/groups/public/</url>
    </repository>
    <repository>
        <id>papermc</id>
        <url>https://repo.papermc.io/repository/maven-public/</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>org.spigotmc</groupId>
        <artifactId>spigot-api</artifactId>
        <version>1.19.2-R0.1-SNAPSHOT</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>com.github.seeseemelk</groupId>
        <artifactId>MockBukkit-v1.19</artifactId>
        <version>2.117.2</version>
        <scope>test</scope>
    </dependency>
</dependencies>
```

**Comment by Insprill** [comment] 2022-09-07 19:18
Duplicate of #462. Put MockBukkit above spigot-api for a temporary fix.

**Closed as not planned** 2022-09-07 19:19 UTC
Labels: duplicate
