### ISSUE TITLE
Could not initialize LibraryLoader (missing dependencies?) when using 1.17 branch

### ISSUE THREAD

**Issue by KotlinFactory** [MockBukkit/MockBukkit#299] opened 2022-02-11 14:19 UTC
Hey,

when using: com.github.seeseemelk:MockBukkit-v1.17:1.13.0

I receive this warning in the console:
```
Feb. 11, 2022 3:15:29 PM org.bukkit.plugin.java.JavaPluginLoader <init>
WARNING: Could not initialize LibraryLoader (missing dependencies?)
```

This means that I can not test plugins that are using the new library functionality properly.

Regards,
 Leonhard

**Comment by TheBusyBiscuit** [comment] 2022-02-11 17:09
Duplicate of #214

**Closed as completed by TheBusyBiscuit** 2022-02-11 17:09 UTC
