### ISSUE TITLE
MockBukkit.loadJar() maybe not working correctly

### ISSUE THREAD

**Issue by Crafter-Y** [MockBukkit/MockBukkit#671] opened 2022-10-19 20:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.18

### Describe the bug

There is a MockBukkit.loadJar() function to load external Plugins that may be required by the project that needs to be tested. It could not load any plugin I tested: LuckPerms-Bukkit-5.3.51, ProtocolLib, worldedit-bukkit-7.2.10

This in it self might not be a bug, because these are very complex plugins wich do a lot on their startup. But it should throw an UnsupportedOperationException or UnimplementedOperationException? 

These are the Exceptions I get:
java.lang.RuntimeException: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader

java.lang.RuntimeException: org.bukkit.plugin.InvalidPluginException: java.lang.ClassCastException: class be.seeseemelk.mockbukkit.plugin.PluginManagerMock cannot be cast to class org.bukkit.plugin.SimplePluginManager (be.seeseemelk.mockbukkit.plugin.PluginManagerMock and org.bukkit.plugin.SimplePluginManager are in unnamed module of loader 'app')

### Reproducible Test

```java
public class MockBukkitTest {
    @DisplayName("Test if MockBukkit can load 3rd party plugins")
    @Test
    public void loadDependencies() {
        MockBukkit.mock();
        MockBukkit.loadJar("testDependencies/LuckPerms-Bukkit-5.3.51.jar");
    }
}
```

```java
public class MockBukkitTest {
    @DisplayName("Test if MockBukkit can load 3rd party plugins")
    @Test
    public void loadDependencies() {
        MockBukkit.mock();
        MockBukkit.loadJar("testDependencies/ProtocolLib.jar");
    }
}
```

**Comment by Crafter-Y** [comment] 2022-10-19 21:16
The first exeption might be explained here #252 but is there no way loading a plugin (as a dependency) without a seperate signature? However, this could still be a problem.

**Comment by Insprill** [comment] 2022-10-19 21:30
The first exception is a duplicate of #642, the second is the plugin casting the PluginManager to CraftBukkit's PluginManager. There's nothing we can do about the latter, that's up to them to not do.

**Closed as completed by Insprill** 2022-10-19 21:30 UTC
