### ISSUE TITLE
Not able to use MockBukkit.mock() method

### ISSUE THREAD

**Issue by B1tstorm** [MockBukkit/MockBukkit#1055] opened 2024-07-28 21:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.20

### Describe the bug

I tried to write a test for my plugin so that I can trigger events (like onPlayerJoin). But after trying out different maven versions I always get this error by executing my test for the onEnable() method.
```
java.lang.NoSuchMethodError: 'void org.bukkit.command.SimpleCommandMap.<init>(org.bukkit.Server, java.util.Map)'

	at be.seeseemelk.mockbukkit.command.MockCommandMap.<init>(MockCommandMap.java:25)
	at be.seeseemelk.mockbukkit.ServerMock.<init>(ServerMock.java:192)
	at be.seeseemelk.mockbukkit.MockBukkit.mock(MockBukkit.java:61)
	at org.example.playgroundplugin.PlaygroundPluginTest.setUp(PlaygroundPluginTest.java:23)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)


Process finished with exit code 255
```

### Reproducible Test

Add maven deps, create a simple test for onEnable(), add 
`    @BeforeEach
    public void setUp()
    {
        server = MockBukkit.mock();
        plugin = MockBukkit.load(PlaygroundPlugin.class);
    }`
, try to execute

**Comment by Insprill** [comment] 2024-07-29 01:01
What version of Paper and MockBukkit are you building against? You need to use a version of MockBukkit that's compatible with the version of Paper you're using.

**Comment by Thorinwasher** [comment] 2024-08-15 14:40
I'm going to close this as not planned. Seems like this was a version issue

**Closed as not planned by Thorinwasher** 2024-08-15 14:40 UTC

**Comment by henriquemb** [comment] 2024-11-19 14:29
I'm having the same problem, the version is correct.

`<dependencies>
    <dependency>
      <groupId>org.spigotmc</groupId>
      <artifactId>spigot-api</artifactId>
      <version>1.21.1-R0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
    
    <dependency>
      <groupId>com.github.seeseemelk</groupId>
      <artifactId>MockBukkit-v1.21</artifactId>
      <version>3.133.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>5.11.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>5.11.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <version>5.11.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-suite</artifactId>
      <version>1.10.3</version>
      <scope>test</scope>
    </dependency>
  </dependencies>`
  
  `public final class MockPluginTestMV extends JavaPlugin {

    @Override
    public void onEnable() {
        // Plugin startup logic
        this.getCommand("test").setExecutor(new TestCommand());
    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic
    }

    public MockPluginTestMV() {
        super();
    }

    public MockPluginTestMV(JavaPluginLoader loader, PluginDescriptionFile description, File dataFolder, File file) {
        super(loader, description, dataFolder, file);
    }
}`

`class TestCommandTest {
    private ServerMock server;
    private MockPluginTestMV plugin;

    @BeforeEach
    void setUp() {
        server = MockBukkit.mock();
        plugin = MockBukkit.load(MockPluginTestMV.class);
    }

    @AfterEach
    void tearDown() {
        MockBukkit.unmock();
    }

    @Test
    void onCommand() {
    }
}`

Error:
`java.lang.NoSuchMethodError: 'void org.bukkit.command.SimpleCommandMap.<init>(org.bukkit.Server, java.util.Map)'
	at be.seeseemelk.mockbukkit.command.MockCommandMap.<init>(MockCommandMap.java:25)
	at be.seeseemelk.mockbukkit.ServerMock.<init>(ServerMock.java:194)
	at be.seeseemelk.mockbukkit.MockBukkit.mock(MockBukkit.java:66)
	at com.github.henriquemb.mockPluginTestMV.TestCommandTest.setUp(TestCommandTest.java:16)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)`

**Comment by thelooter** [comment] 2024-11-19 16:13
You are building against Spigot API, that is an unsupported configuration.

**Comment by henriquemb** [comment] 2024-11-19 16:28
When I use paper, another error occurs
`
java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types: class com.github.henriquemb.ticketsystempremium.TicketSystemPremium

	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:542)
	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:435)
	at org.mockbukkit.mockbukkit.plugin.MockBukkitConfiguredPluginClassLoader.loadProxyClass(MockBukkitConfiguredPluginClassLoader.java:100)
	at org.mockbukkit.mockbukkit.plugin.PluginManagerMock.loadPlugin(PluginManagerMock.java:408)
	at org.mockbukkit.mockbukkit.plugin.PluginManagerMock.loadPlugin(PluginManagerMock.java:473)
	at org.mockbukkit.mockbukkit.MockBukkit.load(MockBukkit.java:190)
	at org.mockbukkit.mockbukkit.MockBukkit.load(MockBukkit.java:175)
	at com.github.henriquemb.ticketsystempremium.database.controller.PlayerControllerTest.setUp(PlayerControllerTest.java:16)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	`

**Comment by henriquemb** [comment] 2024-11-19 18:13
> You are building against Spigot API, that is an unsupported configuration.

I managed to solve the problem, thank you. Could you help with this problem?
java.util.ServiceConfigurationError: io.papermc.paper.registry.RegistryAccess: Provider org.mockbukkit.mockbukkit.registry.RegistryAccessMock could not be instantiated

	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:809)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:725)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1397)
	at java.base/java.util.ServiceLoader.findFirst(ServiceLoader.java:1801)
	at io.papermc.paper.registry.RegistryAccessHolder.<clinit>(RegistryAccessHolder.java:8)
	at io.papermc.paper.registry.RegistryAccess.registryAccess(RegistryAccess.java:24)
	at org.bukkit.Registry.<clinit>(Registry.java:92)
	at org.bukkit.inventory.ItemType.getItemType(ItemType.java:2268)
	at org.bukkit.inventory.ItemType.<clinit>(ItemType.java:96)
	at org.mockbukkit.mockbukkit.inventory.ItemStackMock.<init>(ItemStackMock.java:26)
	at org.mockbukkit.mockbukkit.inventory.ItemStackMock.<clinit>(ItemStackMock.java:31)
	at org.mockbukkit.mockbukkit.inventory.EntityEquipmentMock.<init>(EntityEquipmentMock.java:31)
	at org.mockbukkit.mockbukkit.entity.LivingEntityMock.<init>(LivingEntityMock.java:98)
	at org.mockbukkit.mockbukkit.entity.HumanEntityMock.<init>(HumanEntityMock.java:75)
	at org.mockbukkit.mockbukkit.entity.PlayerMock.<init>(PlayerMock.java:226)
	at org.mockbukkit.mockbukkit.entity.PlayerMockFactory.createRandomPlayer(PlayerMockFactory.java:59)
	at org.mockbukkit.mockbukkit.ServerMock.addPlayer(ServerMock.java:376)
	at com.github.henriquemb.ticketsystempremium.database.controller.PlayerControllerTest.save(PlayerControllerTest.java:34)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:340)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:173)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:785)
	... 20 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
	at org.mockbukkit.mockbukkit.registry.RegistryAccessMock.createClassToKeyConversions(RegistryAccessMock.java:135)
	at org.mockbukkit.mockbukkit.registry.RegistryAccessMock.<clinit>(RegistryAccessMock.java:35)
	... 29 more
	
`class PlayerControllerTest {
    static ServerMock server;
    static TicketSystemPremium plugin;

    static PlayerController playerController = new PlayerController();

    @BeforeAll
    public static void setUpPlugin() {
        server = MockBukkit.mock();
        plugin = MockBukkit.load(TicketSystemPremium.class);
    }

    @AfterAll
    public static void tearDown() {
        MockBukkit.unmock();
    }

    @Test
    void save() throws InterruptedException {
        Player p = server.addPlayer();
    }`
